language: node_js
node_js:
  - 9
cache:
  yarn: true
branches:
  only:
    - master
    - develop
before_script:
  - npm install -g eslint-plugin-react
deploy:
  provider: heroku
  app:
    develop: 'elplano'
  api_key:
    secure: 'd2e63150-c2c8-4481-ae19-76ef8cd9547a'
