language: node_js
node_js:
  - 9
cache:
  yarn: true
branches:
  only:
    - master
    - develop
deploy:
  provider: heroku
  app:
    develop: 'elplano'
  api_key:
    secure: '655c9d12-f926-4cb3-942f-e5552c6be1c6
