language: node_js
node_js:
  - 9
cache:
  yarn: true
branches:
  only:
    - master
    - develop
deploy:
  provider: heroku
  app:
    develop: 'elplano'
  api_key:
    secure: '6baa5bc3-f27c-4a8c-885a-cff811116557'
